PRODUCT_PROPERTY_OVERRIDES +=  \
    dalvik.vm.heapgrowthlimit=192m \
    dalvik.vm.heapmaxfree=8m \
    dalvik.vm.heapminfree=512k \
    dalvik.vm.heapsize=512m \
    dalvik.vm.heapstartsize=8m \
    dalvik.vm.heaptargetutilization=0.75 \
    drm.service.enabled=true \
    media.mediadrmservice.enable=true \
    persist.sys.zram_enabled=1 \
    ro.apex.updatable=true \
    ro.carrier=unknown \
    ro.config.alarm_alert=Alarm_Classic.ogg \
    ro.config.notification_sound=OnTheHunt.ogg \
    ro.control_privapp_permissions=enforce \
    ro.crypto.volume.filenames_mode=aes-256-cts \
    ro.hardware.power=ranchu \
    vendor.rild.libpath=/vendor/lib64/libgoldfish-ril.so \
